APT::FTPArchive::Release::Origin "tynet";
APT::FTPArchive::Release::Label "tynet";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "arm64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Tynet apt repository (GitHub Pages)";
